name: employer_details
description: A mobile application for storing frequently used data of the company where you work.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_ui:
    path: packages/app_ui
  details_repository:
    path: packages/details_repository
  isar_details_api:
    path: packages/isar_details_api
  settings_repository:
    path: packages/settings_repository
  flutter_bloc: ^8.1.3
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  equatable: ^2.0.5
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.3
  flutter_lints: ^2.0.0
  mockingjay: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
