name: details_api
description: API for managing employer details.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.21.0
