name: details_repository
description: Repository for managing employer details.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  cross_file: ^0.3.3+4
  details_api:
    path: ../details_api
  file: ^6.0.0

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0
