name: app_ui
description: UI details of an app.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^5.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockingjay: ^0.3.0
