name: isar_details_api
description: Concrete implementation of the API for managing employer details.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  details_api:
    path: ../details_api
  isar: ^3.1.0+1

dev_dependencies:
  build_runner: ^2.4.4
  isar_generator: ^3.1.0+1
  lints: ^2.0.0
  test: ^1.21.0
